[package]
name = "phone-backup-gui"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-shell = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow.workspace = true
phone-backup-application = { workspace = true }
phone-backup-domain = { workspace = true }

[build-dependencies]
tauri-build = "2.0"
