[package]
name = "phone-backup-gui"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-shell = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow.workspace = true
application = { workspace = true }
domain = { workspace = true }
ports = { workspace = true }
adapter-adb = { workspace = true }
adapter-database-sqlite = { workspace = true }
adapter-filesystem = { workspace = true }
adapter-mock = { workspace = true }
adapter-opendal = { workspace = true }
axum.workspace = true
socketioxide.workspace = true
tower.workspace = true
tower-http.workspace = true
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
