[package]
name = "phone-backup-adapter-mock"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { workspace = true }
ports = { workspace = true }
scanner-engine = { workspace = true }
anyhow.workspace = true
chrono.workspace = true
