[package]
name = "phone-backup-adapter-adb"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { workspace = true }
ports = { workspace = true }
anyhow.workspace = true
chrono.workspace = true
uuid.workspace = true
which.workspace = true
mime_guess.workspace = true
tracing.workspace = true
