[package]
name = "phone-backup-adapter-filesystem"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { workspace = true }
ports = { workspace = true }
anyhow.workspace = true
chrono.workspace = true
walkdir.workspace = true
mime_guess.workspace = true

[dev-dependencies]
tempfile.workspace = true
