[package]
name = "phone-backup-application"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { path = "../domain", package = "phone-backup-domain", version = "0.1.0" }
ports = { path = "../ports", package = "phone-backup-ports", version = "0.1.0" }
anyhow.workspace = true
chrono.workspace = true
sha2.workspace = true
zstd.workspace = true
mime_guess.workspace = true
aes-gcm.workspace = true
argon2.workspace = true
rand.workspace = true
kamadak-exif.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
indicatif.workspace = true
rayon.workspace = true
