[package]
name = "phone-backup-adapter-mock"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { path = "../../core/domain", package = "phone-backup-domain", version = "0.3.0" }
ports = { path = "../../core/ports", package = "phone-backup-ports", version = "0.3.0" }
anyhow.workspace = true
chrono.workspace = true
