[package]
name = "phone-backup-adapter-database-sqlite"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { workspace = true }
ports = { workspace = true }
anyhow.workspace = true
rusqlite.workspace = true
chrono.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }
r2d2 = "0.8"
r2d2_sqlite = "0.24"
