[package]
name = "phone-backup-adapter-database-sqlite"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { workspace = true, package = "phone-backup-domain" }
ports = { workspace = true, package = "phone-backup-ports" }
anyhow.workspace = true
rusqlite.workspace = true
chrono.workspace = true
serde_json.workspace = true
tracing.workspace = true
