[package]
name = "phone-backup"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "phone-backup"
path = "src/main.rs"

[dependencies]
domain = { path = "../../core/domain", package = "phone-backup-domain", version = "0.3.1" }
ports = { path = "../../core/ports", package = "phone-backup-ports", version = "0.3.1" }
application = { path = "../../core/application", package = "phone-backup-application", version = "0.3.1" }
adapter-mock = { path = "../../adapters/mock", package = "phone-backup-adapter-mock", version = "0.3.1" }
adapter-adb = { path = "../../adapters/adb", package = "phone-backup-adapter-adb", version = "0.3.1" }
adapter-filesystem = { path = "../../adapters/filesystem", package = "phone-backup-adapter-filesystem", version = "0.3.1" }
adapter-opendal = { path = "../../adapters/opendal", package = "phone-backup-adapter-opendal", version = "0.3.1" }
adapter-database-sqlite = { path = "../../infrastructure/database-sqlite", package = "phone-backup-adapter-database-sqlite", version = "0.3.1" }
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
