[package]
name = "phone-backup"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "phone-backup"
path = "src/main.rs"

[dependencies]
domain = { workspace = true, package = "phone-backup-domain" }
ports = { workspace = true, package = "phone-backup-ports" }
application = { workspace = true, package = "phone-backup-application" }
adapter-mock = { workspace = true, package = "phone-backup-adapter-mock" }
adapter-adb = { workspace = true, package = "phone-backup-adapter-adb" }
adapter-filesystem = { workspace = true, package = "phone-backup-adapter-filesystem" }
adapter-opendal = { workspace = true, package = "phone-backup-adapter-opendal" }
adapter-database-sqlite = { workspace = true, package = "phone-backup-adapter-database-sqlite" }

clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
