[[permission]]
identifier = "allow-app-commands"
description = "Allows all custom app commands"
commands.allow = [
    "get_devices",
    "get_storage_stats",
    "get_snapshots",
    "start_backup",
    "delete_snapshot",
    "prune_failed_snapshots",
    "run_gc",
    "restore_snapshot",
    "get_doctor_report",
    "generate_keys",
    "add_schedule",
    "get_snapshot_files",
    "get_structured_data",
    "get_live_data",
    "get_live_apps",
    "get_device_battery",
    "browse_directory",
    "delete_device_file",
    "rename_device_file",
    "copy_device_file",
    "upload_to_device",
    "download_from_device",
    "calculate_device_file_hash",
    "get_snapshot_apps",
    "get_file_diff",
    "search_files",
    "scan_device",
    "switch_to_mock_storage",
    "switch_to_s3_storage",
    "search_contacts"
]
