[package]
name = "phone-backup-adapter-opendal"
version.workspace = true
edition.workspace = true
description = "A StoragePort implementation using OpenDAL for multi-cloud support."
license.workspace = true
repository.workspace = true

[dependencies]
ports = { workspace = true }
opendal.workspace = true
anyhow.workspace = true
